### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by jm-riley** [hegelocampus/WikiArtClone#1]
### `artists`
- [x] index on nationality (remember there is a trade off with indexing when it comes to inserting, updating, and deleting). think about how often you'll be querying based on these columns and decide whether all of these indexes are necessary

### `artworks`
- [x] specify that `genre_id` references `genre`

### `artwork_styles`
- [x] if an artwork can have multiple styles, we shouldn't have a 'unique' constraint on `artwork_id` && `style_id`

Nice work! I think this will be a really cool project :)

**Comment by hegelocampus** [comment]
Added all recommendations! Thanks JM!
