### ISSUE TITLE
Sample State Shape

### ISSUE THREAD

**Issue by jm-riley** [hegelocampus/WikiArtClone#2]
### `user`
- [x] `users` slice of state should be set up to store data on multiple users
```javascript
{users: 
   1: { id: 1, username: 'something', favorite_artwork_album_ids: [32, 45, 22] },
   2: { id: 2, username: 'something_else', favorite_artwork_album_ids: [7, 22, 14] }
}
```
- [x] every entity should have it's own slice of state. let's avoid nesting duplicate data. for example, instead of nesting `artist_artworks`, we would have a key of `artwork_ids` with an array of ids

- [x] we don't need a slice of state for `artist` and `artwork`, only `artists` and `artworks`

- [x] you'll need a way to handle the favorite albums, most likely another entity that stores the albums, and an array of `artwork_ids` that it contains

Let me know if you have any questions and we can go over some things :)

**Comment by hegelocampus** [comment]
I believe the most recent commit mends all these issues. 
Thanks JM!
