### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by hegelocampus** [hegelocampus/WikiArtClone#3]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by hegelocampus** [comment]
Styling is now _mostly_ done, I'd like to add an 'x' to the modal as a clear way to close it and I'd like to implement a dark theme on my webpage to distinguish it from the original website.

**Comment by jm-riley** [comment]
- [x] add `Sign In` text next to the login button in your navbar
- [x] incorporate error messages from the backend into your forms
- [x] add a little extra padding on your input fields (and increase font-size), decrease the height of your form to get rid of the extra whitespace

Looking great, Bee

**Comment by jm-riley** [comment]
- [x] make form errors more visible
- [x] form errors should clear when switching between login / signup forms
- [x] can't see navbar dropdown with the new black background
- [x] dropdown should close when a user clicks anywhere else on the screen
